apiVersion: v1
kind: Namespace
metadata:
  name: retailpulse
  labels:
    name: retailpulse
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: retailpulse-config
  namespace: retailpulse
data:
  MLFLOW_TRACKING_URI: "http://mlflow.retailpulse.svc.cluster.local:5000"
  DATABASE_URL: "postgresql://retailpulse:retailpulse123@postgres.retailpulse.svc.cluster.local:5432/retailpulse"
  REDIS_URL: "redis://redis.retailpulse.svc.cluster.local:6379"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: retailpulse-secrets
  namespace: retailpulse
type: Opaque
stringData:
  POSTGRES_PASSWORD: "retailpulse123"
  REDIS_PASSWORD: ""
  MLFLOW_S3_ENDPOINT_URL: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""